fileGroups:
- Logger-iOS
targets:
  Logger-iOS:
    type: application
    platform: iOS
    sources:
    - Logger-iOS/Sources
    - Logger-iOS/Support/Assets.xcassets
    - Logger-iOS/Support/LaunchScreen.storyboard
    settings:
      PRODUCT_NAME: Logger
      PRODUCT_BUNDLE_IDENTIFIER: run.nathan.$(PRODUCT_NAME)
      INFOPLIST_FILE: $(SRCROOT)/Logger-iOS/Support/Info.plist
      DEVELOPMENT_TEAM: 294VZ3T33E
      IPHONEOS_DEPLOYMENT_TARGET: 11.0
      OTHER_SWIFT_FLAGS: "-Onone -Xfrontend -warn-long-function-bodies=100 -Xfrontend -warn-long-expression-type-checking=100"
    scheme:
      testTargets:
      - Logger-iOSTests
    dependencies:
    - target: LoggerKit
    - target: SQLite
    - target: Differ
    - target: Attributed
    postbuildScripts:
    - path: Scripts/increment-build.sh
      name: Increment Build
      runOnlyWhenInstalling: true
  
  Logger-iOSTests:
    type: bundle.unit-test
    platform: iOS
    sources: 
    - Logger-iOS/Tests
    settings:
      INFOPLIST_FILE: Logger-iOS/Support/Tests-Info.plist
      IPHONEOS_DEPLOYMENT_TARGET: 11.0
    dependencies:
    - target: Logger-iOS
  
