fileGroups:
  - LoggerKit
targets:
  LoggerKit:
    type: framework
    platform: iOS
    sources: 
      - LoggerKit/Sources
    settings:
      INFOPLIST_FILE: LoggerKit/Support/Info.plist
      IPHONEOS_DEPLOYMENT_TARGET: 11.0
    scheme:
      testTargets:
        - LoggerKitTests
    dependencies:
      - target: SQLite

  LoggerKitTests:
    type: bundle.unit-test
    platform: iOS
    sources: 
      - LoggerKit/Tests
    settings:
      INFOPLIST_FILE: LoggerKit/Support/Tests-Info.plist
      IPHONEOS_DEPLOYMENT_TARGET: 11.0
    dependencies:
      - target: LoggerKit
